version: "3.9"

volumes:
  moeny_lover_data: {}
# networks:
#   money_lover-net:

services:
  db:
    container_name: money_lover_pg_db
    image: postgres:13-alpine
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    # networks:
    #   - moeny_lover-net
    volumes:
      - moeny_lover_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=money_lover_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwer1234
    ports:
      - "5432:5432"

  web:
    container_name: money_lover_django_web
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
