# Generated by Django 3.2.4 on 2021-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_lover_app', '0002_remove_transaction_is_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
    ]
