# Generated by Django 3.2.4 on 2021-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_lover_app', '0003_transaction_is_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='owner',
        ),
    ]
